// =========================================
// Tax Calculation Constants
// =========================================

export const TAX_CONSTANTS = {
  KORFBEPERKING_THRESHOLD: 1000000,
  KORFBEPERKING_RATE: 0.7,
  STANDARD_INCREASE_RATE: 0.09,
  QUARTERLY_RATES: {
    Q1: 0.12,
    Q2: 0.10,
    Q3: 0.08,
    Q4: 0.06,
    TOTAL: 0.36
  },
  LIQUIDATION_RESERVE_RATE: 0.10,
  DE_MINIMIS_THRESHOLD: 50,
  DE_MINIMIS_PERCENTAGE: 0.005,
  REDUCED_RATE_THRESHOLD: 100000,
  REDUCED_RATE: 0.20,
  STANDARD_RATE: 0.25,
  REQUIRED_PREPAYMENTS_PERCENTAGE: 0.9
} as const;

export const FIELD_CODES = {
  BESTANDDELEN_VH_RESULTAAT_AFTREKBEPERKING: '1420',
  RESTEREND_RESULTAAT: '1430',
  GRONDSLAG_VOOR_BEREKENING_KORF: '1440',
  BELASTBARE_WINST_GEWOON_TARIEF: '1460',
  LIQUIDATIERESERVE: '1508',
  NIET_TERUGBETAALBARE_VOORHEFFING: '1830',
  TERUGBETAALBARE_VOORHEFFING: '1840'
} as const;

export const SECTION_INDICES = {
  RESULTAAT_VAN_HET_BELASTBARE_TIJDPERK: 0,
  AFTREKKEN_VAN_DE_RESTERENDE_WINST: 3,
  AFTREKKEN_RESTERENDE_WINST_KORFBEPERKING: 5,
  AFZONDERLIJK_TE_BELASTEN: 7,
  VOORHEFFING: 8
} as const;

export const STEP_CONFIG = {
  MIN_STEP: 1,
  MAX_STEP: 3,
  STEPS: {
    SELECT_INVOERMETHODE: 1,
    VEREENVOUDIGDE_AANGIFTE: 2,
    VOORSCHOTTEN_OPTIMALISEREN: 3
  }
} as const; 